# -*- coding: utf-8 -*-
"""GO_annotation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKTYOa8Y_a3S-JO1d28IetKgVEzDuZaA

### Mount Google Drive

To access files stored in your Google Drive, you first need to mount it. This will prompt you to authenticate your Google account.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Load Data from Google Drive

Once your Google Drive is mounted, you can load data from files, for example, a CSV file, using pandas. Make sure to replace `'/content/drive/MyDrive/path/to/your/file.csv'` with the actual path to your file in Google Drive.
"""

import pandas as pd

# Replace 'path/to/your/file.csv' with the actual path to your CSV file in Google Drive
# For example: '/content/drive/MyDrive/my_data/data.csv'
file_path = '/content/drive/MyDrive/Colab Notebooks/idr_class_lists/class_01.txt'
df = pd.read_csv(file_path, header=None) # Load without a header, so the first row becomes data

# Rename the column (which will be '0' by default since header=None was used) to '1'
#df.columns = [1]

# Display the first 5 rows of the DataFrame
display(df.head())

df['ID_Part'] = df.iloc[:, 0].astype(str).str.split('_').str[0]
display(df.head())

id_part_list = df['ID_Part'].tolist()
id_part_list = list(set(id_part_list)) # Remove duplicates
print(id_part_list)

output_file_path = '/content/drive/MyDrive/final_IDRs_GO/ids_class_01.txt'

with open(output_file_path, 'w') as f:
    for item in id_part_list:
        f.write(f"{item}\n")

print(f"ID_Part list saved to: {output_file_path}")

import pandas as pd
import os

input_dir = '/content/drive/MyDrive/Colab Notebooks/idr_class_lists/'
output_dir = '/content/drive/MyDrive/final_IDRs_GO/'

# Create the output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

for i in range(1, 19):
    input_filename = f'class_{i:02d}.txt'
    output_filename = f'ids_class_{i:02d}.txt'

    file_path = os.path.join(input_dir, input_filename)
    output_file_path = os.path.join(output_dir, output_filename)

    print(f"Processing {input_filename}...")

    try:
        # Load data without header
        df = pd.read_csv(file_path, header=None)

        # Extract ID_Part
        df['ID_Part'] = df.iloc[:, 0].astype(str).str.split('_').str[0]

        # Get unique ID_Part list
        id_part_list = df['ID_Part'].tolist()
        id_part_list = list(set(id_part_list)) # Remove duplicates

        # Save to file
        with open(output_file_path, 'w') as f:
            for item in id_part_list:
                f.write(f"{item}\n")

        print(f"ID_Part list saved to: {output_file_path}")
    except FileNotFoundError:
        print(f"Error: {input_filename} not found. Skipping.")
    except Exception as e:
        print(f"An error occurred while processing {input_filename}: {e}")

print("All files processed.")

"""### Load and Visualize GO Enrichment Results

Now, let's load one of the `analysis_XX.txt` files, which contain GO enrichment results. We need to parse these files by finding a specific marker line (`"GO biological process complete"`) and then loading the table data that follows.

For demonstration, we will process `analysis_01.txt`.
"""

import pandas as pd
import os
import io
import matplotlib.pyplot as plt
import seaborn as sns

analysis_input_dir = '/content/drive/MyDrive/Colab Notebooks/Classes_GO_annotation/' # Assuming this is the directory
analysis_filename = 'analysis_01.txt'
analysis_file_path = os.path.join(analysis_input_dir, analysis_filename)

marker_line = 'GO biological process complete'
data_lines = []
found_marker = False

try:
    with open(analysis_file_path, 'r') as f:
        for line in f:
            if found_marker:
                data_lines.append(line)
            if marker_line in line:
                found_marker = True

    if not found_marker:
        print(f"Error: Marker '{marker_line}' not found in {analysis_filename}")
    elif not data_lines:
        print(f"Error: No data found after marker in {analysis_filename}")
    else:
        # Read the data into a pandas DataFrame, assuming tab-separated values
        # and no header, as the first line is data.
        # Manually assign column names for clarity and correct processing.
        column_names = [
            'Term',
            'Genes in study',
            'Genes in background',
            'P-value',
            'Significance',
            'Fold Enrichment',
            'Raw P-value',
            'FDR'
        ]
        go_df = pd.read_csv(io.StringIO(''.join(data_lines)), sep='\t', header=None)
        go_df.columns = column_names[:len(go_df.columns)] # Assign names up to the number of columns found

        # Convert 'Fold Enrichment' to numeric, coercing errors to NaN
        go_df['Fold Enrichment'] = pd.to_numeric(go_df['Fold Enrichment'], errors='coerce')
        # Drop rows where 'Fold Enrichment' could not be converted (e.g., non-numeric values like '< 0.01')
        go_df.dropna(subset=['Fold Enrichment'], inplace=True)

        print("DataFrame dtypes after processing:")
        print(go_df.dtypes)
        display(go_df.head())

except FileNotFoundError:
    print(f"Error: {analysis_filename} not found in {analysis_input_dir}")
    print(f"Please check if '{analysis_filename}' exists in the directory '{analysis_input_dir}'.")
    try:
        print(f"Contents of '{analysis_input_dir}':")
        for item in os.listdir(analysis_input_dir):
            print(f"- {item}")
    except FileNotFoundError:
        print(f"Directory '{analysis_input_dir}' itself was not found. Please ensure the path is correct.")
    except Exception as list_e:
        print(f"Could not list directory contents: {list_e}")
except Exception as e:
    print(f"An error occurred while processing {analysis_filename}: {e}")

"""Now, let's extract the top 5 GO terms based on 'Fold Enrichment' and visualize them."""

# Sort by 'Fold Enrichment' in descending order and get the top 5
# Assuming 'Term' is the GO term description and 'Fold Enrichment' is the enrichment score column.
# Adjust column names if they are different in your actual file.

if 'Fold Enrichment' in go_df.columns and 'Term' in go_df.columns:
    top_5_go_terms = go_df.sort_values(by='Fold Enrichment', ascending=False).head(5)

    print("Top 5 GO Terms by Fold Enrichment:")
    display(top_5_go_terms)

    # Create a bar graph
    plt.figure(figsize=(12, 7))
    sns.barplot(x='Fold Enrichment', y='Term', data=top_5_go_terms, palette='viridis')
    plt.title(f'Top 5 GO Biological Process Terms by Fold Enrichment for {analysis_filename}')
    plt.xlabel('Fold Enrichment')
    plt.ylabel('GO Term')
    plt.tight_layout()
    plt.show()
else:
    print("Required columns ('Term' or 'Fold Enrichment') not found in the DataFrame. Please check the file format.")

"""### Batch Processing and Plotting GO Enrichment Results

Now, let's automate the process to generate plots for all `analysis_01.txt` through `analysis_17.txt` files. The loop will process each file, extract the top 5 GO terms by 'Fold Enrichment', and save the bar graph to a specified output directory.
"""

import pandas as pd
import os
import io
import matplotlib.pyplot as plt
import seaborn as sns

# Define input and output directories
analysis_input_dir = '/content/drive/MyDrive/Colab Notebooks/Classes_GO_annotation/'
output_plot_dir = '/content/drive/MyDrive/final_IDRs_GO/go_enrichment_plots/'

# Create the output directory if it doesn't exist
os.makedirs(output_plot_dir, exist_ok=True)

marker_line = 'GO biological process complete'

# Define column names based on the typical GO enrichment output format
column_names = [
    'Term',
    'Genes in study',
    'Genes in background',
    'P-value',
    'Significance',
    'Fold Enrichment',
    'Raw P-value',
    'FDR'
]

all_top_go_terms_list = [] # List to store top GO terms from all files

for i in range(1, 18): # Loop from analysis_01.txt to analysis_17.txt
    analysis_filename = f'analysis_{i:02d}.txt'
    analysis_file_path = os.path.join(analysis_input_dir, analysis_filename)

    print(f"\nProcessing {analysis_filename}...")

    data_lines = []
    found_marker = False
    go_df = pd.DataFrame()

    try:
        with open(analysis_file_path, 'r') as f:
            for line in f:
                if found_marker:
                    data_lines.append(line)
                if marker_line in line:
                    found_marker = True

        if not found_marker:
            print(f"Error: Marker '{marker_line}' not found in {analysis_filename}. Skipping.")
            continue
        elif not data_lines:
            print(f"Error: No data found after marker in {analysis_filename}. Skipping.")
            continue

        # Read the data into a pandas DataFrame
        go_df = pd.read_csv(io.StringIO(''.join(data_lines)), sep='\t', header=None)
        go_df.columns = column_names[:len(go_df.columns)] # Assign names up to the number of columns found

        # Convert 'Fold Enrichment' to numeric, coercing errors to NaN
        go_df['Fold Enrichment'] = pd.to_numeric(go_df['Fold Enrichment'], errors='coerce')
        # Drop rows where 'Fold Enrichment' could not be converted (e.g., non-numeric values like '< 0.01')
        go_df.dropna(subset=['Fold Enrichment'], inplace=True)

        if go_df.empty:
            print(f"No valid data remaining in {analysis_filename} after cleaning. Skipping.")
            continue

        # Sort by 'Fold Enrichment' and get the top 5
        if 'Fold Enrichment' in go_df.columns and 'Term' in go_df.columns:
            top_5_go_terms = go_df.sort_values(by='Fold Enrichment', ascending=False).head(5)

            if top_5_go_terms.empty:
                print(f"No top 5 GO terms found for {analysis_filename}. Skipping data collection.")
                continue

            # Add an 'Analysis' column to identify the source file
            top_5_go_terms['Analysis'] = f'Analysis {i:02d}'
            all_top_go_terms_list.append(top_5_go_terms)
            print(f"Top 5 GO terms collected for {analysis_filename}.")
        else:
            print(f"Required columns ('Term' or 'Fold Enrichment') not found in {analysis_filename}. Skipping data collection.")

    except FileNotFoundError:
        print(f"Error: {analysis_filename} not found in {analysis_input_dir}. Skipping.")
    except Exception as e:
        print(f"An error occurred while processing {analysis_filename}: {e}. Skipping.")

print("\nAll analysis files processed.")

# Concatenate all collected top GO terms into a single DataFrame
if all_top_go_terms_list:
    combined_go_df = pd.concat(all_top_go_terms_list, ignore_index=True)
    print("Combined DataFrame of top GO terms created.")
else:
    print("No top GO terms were collected from any analysis files.")

import matplotlib.pyplot as plt
import seaborn as sns
import os

# Define the output plot directory (same as in the previous cell)
output_plot_dir = '/content/drive/MyDrive/final_IDRs_GO/go_enrichment_plots/'

# Ensure the combined_go_df exists
if 'combined_go_df' in locals() and not combined_go_df.empty:
    # Define the mapping for analysis names
    analysis_name_mapping = {
        'Analysis 01': 'Nuclear speckle',
        'Analysis 02': 'Photobodies',
        'Analysis 03': 'ELF3 condensates',
        'Analysis 05': 'FCA condensates',
        'Analysis 06': 'Nucleolus',
        'Analysis 07': 'D-bodies (Dicing bodies)',
        'Analysis 08': 'Cajal bodies',
        'Analysis 11': 'SINCs (SA-induced NPR1 condensates)',
        'Analysis 14': 'P-bodies (Processing bodies)',
        'Analysis 17': 'STT condensates'
    }

    # Apply the mapping to the 'Analysis' column
    combined_go_df['Analysis'] = combined_go_df['Analysis'].map(analysis_name_mapping).fillna(combined_go_df['Analysis'])

    plt.figure(figsize=(25, 12)) # Increased figure size further for more labels

    # Set font sizes for better readability
    plt.rcParams['axes.titlesize'] = 16
    plt.rcParams['axes.labelsize'] = 14
    plt.rcParams['xtick.labelsize'] = 8 # Smaller x-axis labels
    plt.rcParams['ytick.labelsize'] = 10
    plt.rcParams['legend.fontsize'] = 10 # Smaller legend font size

    # Sort the combined_go_df to ensure contiguous blocks of analysis terms
    # First sort by 'Analysis' and then by 'Fold Enrichment' within each analysis
    sorted_df = combined_go_df.sort_values(by=['Analysis', 'Fold Enrichment'], ascending=[True, False])
    sorted_df['Combined_Label'] = sorted_df['Term'].apply(lambda x: x.split(' (GO:')[0]) # Use only the term description, not GO ID

    # Create a unique index for plotting, to ensure each bar has its own position
    sorted_df['plot_index'] = range(len(sorted_df))

    sns.barplot(
        data=sorted_df,
        x='Fold Enrichment', # Flipped axis
        y='plot_index',  # Plot against the unique index
        hue='Analysis', # Use 'Analysis' to differentiate the bars
        palette='viridis',
        dodge=False # Important: ensures each Combined_Label gets one bar, colored by its Analysis
    )

    plt.title('Top 5 GO Biological Process Terms by Fold Enrichment Across All Analyses (Vertical)') # Updated title
    plt.xlabel('Fold Enrichment') # Flipped label
    plt.ylabel('GO Term (Grouped by Analysis)') # Flipped label

    # Set y-axis ticks and labels using the Combined_Label from the sorted DataFrame
    plt.yticks(ticks=sorted_df['plot_index'], labels=sorted_df['Combined_Label'], rotation=0, ha='right')
    plt.legend(title='Analysis File', bbox_to_anchor=(1.01, 1), loc='upper left') # Place legend outside, adjusted slightly

    # Add horizontal lines to separate analyses
    ax = plt.gca() # Get the current axes
    # Calculate group boundaries dynamically
    group_indices = sorted_df.groupby('Analysis').size().cumsum().tolist()
    # The lines should be placed before the start of each new group
    line_positions = [idx - 0.5 for idx in group_indices[:-1]] # Exclude the last cumulative sum as it's the total number of rows

    for pos in line_positions:
        ax.axhline(y=pos, color='grey', linestyle='--', linewidth=1.5, alpha=0.7)


    plt.tight_layout() # Adjust layout to prevent overlapping elements

    combined_plot_output_path = os.path.join(output_plot_dir, 'combined_top5_go_terms_single_plot_large_separated_renamed_vertical.png')
    plt.savefig(combined_plot_output_path)
    plt.show()
    print(f"Combined plot saved to: {combined_plot_output_path}")
else:
    print("No combined data to plot. The 'combined_go_df' is either not created or empty.")

"""### Combined Horizontal Plot for Original GO Enrichment Results"""

import matplotlib.pyplot as plt
import seaborn as sns
import os

output_plot_dir = '/content/drive/MyDrive/final_IDRs_GO/go_enrichment_plots/'

if 'combined_go_df' in locals() and not combined_go_df.empty:
    analysis_name_mapping = {
        'Analysis 01': 'Nuclear speckle',
        'Analysis 02': 'Photobodies',
        'Analysis 03': 'ELF3 condensates',
        'Analysis 05': 'FCA condensates',
        'Analysis 06': 'Nucleolus',
        'Analysis 07': 'D-bodies (Dicing bodies)',
        'Analysis 08': 'Cajal bodies',
        'Analysis 11': 'SINCs (SA-induced NPR1 condensates)',
        'Analysis 14': 'P-bodies (Processing bodies)',
        'Analysis 17': 'STT condensates'
    }
    combined_go_df['Analysis'] = combined_go_df['Analysis'].map(analysis_name_mapping).fillna(combined_go_df['Analysis'])

    plt.figure(figsize=(25, 12))

    plt.rcParams['axes.titlesize'] = 16
    plt.rcParams['axes.labelsize'] = 14
    plt.rcParams['xtick.labelsize'] = 10
    plt.rcParams['ytick.labelsize'] = 8
    plt.rcParams['legend.fontsize'] = 10

    sorted_df = combined_go_df.sort_values(by=['Analysis', 'Fold Enrichment'], ascending=[True, False])
    sorted_df['Combined_Label'] = sorted_df['Term'].apply(lambda x: x.split(' (GO:')[0])

    # Create a unique index for plotting, to ensure each bar has its own position
    sorted_df['plot_index'] = range(len(sorted_df))

    sns.barplot(
        data=sorted_df,
        x='plot_index', # Plot against the unique index
        y='Fold Enrichment',
        hue='Analysis',
        palette='viridis',
        dodge=False
    )

    plt.title('Top 5 GO Biological Process Terms by Fold Enrichment Across All Analyses (Horizontal)')
    plt.xlabel('GO Term (Grouped by Analysis)')
    plt.ylabel('Fold Enrichment')

    # Set x-axis ticks and labels using the Combined_Label from the sorted DataFrame
    plt.xticks(ticks=sorted_df['plot_index'], labels=sorted_df['Combined_Label'], rotation=90, ha='center')
    plt.legend(title='Analysis File', bbox_to_anchor=(1.01, 1), loc='upper left')

    # Add vertical lines to separate analyses
    ax = plt.gca()
    # Calculate group boundaries dynamically
    group_indices = sorted_df.groupby('Analysis').size().cumsum().tolist()
    # The lines should be placed before the start of each new group
    line_positions = [idx - 0.5 for idx in group_indices[:-1]] # Exclude the last cumulative sum as it's the total number of rows

    for pos in line_positions:
        ax.axvline(x=pos, color='grey', linestyle='--', linewidth=1.5, alpha=0.7)

    plt.tight_layout()

    combined_plot_output_path_horizontal = os.path.join(output_plot_dir, 'combined_top5_go_terms_single_plot_large_separated_renamed_horizontal.png')
    plt.savefig(combined_plot_output_path_horizontal)
    plt.show()
    print(f"Combined horizontal plot saved to: {combined_plot_output_path_horizontal}")
else:
    print("No combined data to plot for the original analysis files. The 'combined_go_df' is either not created or empty.")

"""### Batch Processing and Plotting GO Enrichment Results for a New Folder

Now, let's automate the process to generate plots for all `analysis_01.txt` through `analysis_17.txt` files from the new input directory. The loop will process each file, extract the top 5 GO terms by 'Fold Enrichment', and save the bar graph to a specified output directory.
"""

import pandas as pd
import os
import io
import matplotlib.pyplot as plt
import seaborn as sns

# Define new input and output directories
new_analysis_input_dir = '/content/drive/MyDrive/final_IDRs_GO/Unknown_GO_annotation/'
new_output_plot_dir = '/content/drive/MyDrive/final_IDRs_GO/go_enrichment_plots_unknown/'

# Create the output directory if it doesn't exist
os.makedirs(new_output_plot_dir, exist_ok=True)

marker_line = 'GO biological process complete'

# Define column names based on the typical GO enrichment output format
column_names = [
    'Term',
    'Genes in study',
    'Genes in background',
    'P-value',
    'Significance',
    'Fold Enrichment',
    'Raw P-value',
    'FDR'
]

all_top_go_terms_list_new = [] # List to store top GO terms from all files in the new folder

for i in range(1, 4): # Loop from analysis_unknown_1.txt to analysis_unknown_3.txt
    analysis_filename = f'analysis_unknown_{i}.txt'
    analysis_file_path = os.path.join(new_analysis_input_dir, analysis_filename)

    print(f"\nProcessing {analysis_filename} from new folder...")

    data_lines = []
    found_marker = False
    go_df_new = pd.DataFrame() # Use a new DataFrame variable

    try:
        with open(analysis_file_path, 'r') as f:
            for line in f:
                if found_marker:
                    data_lines.append(line)
                if marker_line in line:
                    found_marker = True

        if not found_marker:
            print(f"Error: Marker '{marker_line}' not found in {analysis_filename}. Skipping.")
            continue
        elif not data_lines:
            print(f"Error: No data found after marker in {analysis_filename}. Skipping.")
            continue

        # Read the data into a pandas DataFrame
        go_df_new = pd.read_csv(io.StringIO(''.join(data_lines)), sep='\t', header=None)
        go_df_new.columns = column_names[:len(go_df_new.columns)] # Assign names up to the number of columns found

        # Convert 'Fold Enrichment' to numeric, coercing errors to NaN
        go_df_new['Fold Enrichment'] = pd.to_numeric(go_df_new['Fold Enrichment'], errors='coerce')
        # Drop rows where 'Fold Enrichment' could not be converted (e.g., non-numeric values like '< 0.01')
        go_df_new.dropna(subset=['Fold Enrichment'], inplace=True)

        if go_df_new.empty:
            print(f"No valid data remaining in {analysis_filename} after cleaning. Skipping.")
            continue

        # Sort by 'Fold Enrichment' and get the top 5
        if 'Fold Enrichment' in go_df_new.columns and 'Term' in go_df_new.columns:
            top_5_go_terms_new = go_df_new.sort_values(by='Fold Enrichment', ascending=False).head(5)

            if top_5_go_terms_new.empty:
                print(f"No top 5 GO terms found for {analysis_filename}. Skipping data collection.")
                continue

            # Add an 'Analysis' column to identify the source file
            top_5_go_terms_new['Analysis'] = f'Analysis {i}' # Changed to use i directly as it's not zero-padded anymore
            all_top_go_terms_list_new.append(top_5_go_terms_new)
            print(f"Top 5 GO terms collected for {analysis_filename}.")
        else:
            print(f"Required columns ('Term' or 'Fold Enrichment') not found in {analysis_filename}. Skipping data collection.")

    except FileNotFoundError:
        print(f"Error: {analysis_filename} not found in {new_analysis_input_dir}. Skipping.")
    except Exception as e:
        print(f"An error occurred while processing {analysis_filename}: {e}. Skipping.")

print("\nAll analysis files processed from new folder.")

# Concatenate all collected top GO terms into a single DataFrame
if all_top_go_terms_list_new:
    combined_go_df_new = pd.concat(all_top_go_terms_list_new, ignore_index=True)
    print("Combined DataFrame of top GO terms for new folder created.")
else:
    print("No top GO terms were collected from any analysis files in the new folder.")

"""### Combined Plot for the New Folder

Here is the combined plot for the GO enrichment results from the new folder. Note that the analysis names are generic ('Analysis XX') unless a specific mapping is provided for these new files.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import os

# Define the output plot directory (same as in the previous cell)
new_output_plot_dir = '/content/drive/MyDrive/final_IDRs_GO/go_enrichment_plots_unknown/'

# Ensure the combined_go_df_new exists
if 'combined_go_df_new' in locals() and not combined_go_df_new.empty:
    # !!! IMPORTANT: If you have specific names for 'Analysis 01', 'Analysis 02', etc. in this NEW folder,
    # uncomment and modify this mapping dictionary. Otherwise, generic 'Analysis XX' labels will be used.
    # For this example, we'll keep the 'Analysis XX' labels as we don't have new names yet.
    # analysis_name_mapping_new = {
    #     'Analysis 01': 'New Class A',
    #     'Analysis 02': 'New Class B',
    #     # ... add more mappings as needed
    # }
    # combined_go_df_new['Analysis'] = combined_go_df_new['Analysis'].map(analysis_name_mapping_new).fillna(combined_go_df_new['Analysis'])

    plt.figure(figsize=(25, 12)) # Increased figure size further for more labels

    # Set font sizes for better readability
    plt.rcParams['axes.titlesize'] = 16
    plt.rcParams['axes.labelsize'] = 14
    plt.rcParams['xtick.labelsize'] = 8 # Smaller x-axis labels
    plt.rcParams['ytick.labelsize'] = 10
    plt.rcParams['legend.fontsize'] = 10 # Smaller legend font size

    # Sort the combined_go_df_new to ensure contiguous blocks of analysis terms
    # First sort by 'Analysis' and then by 'Fold Enrichment' within each analysis
    sorted_df_new = combined_go_df_new.sort_values(by=['Analysis', 'Fold Enrichment'], ascending=[True, False])
    sorted_df_new['Combined_Label'] = sorted_df_new['Term'].apply(lambda x: x.split(' (GO:')[0]) # Use only the term description, not GO ID

    # Create a unique index for plotting, to ensure each bar has its own position
    sorted_df_new['plot_index'] = range(len(sorted_df_new))

    sns.barplot(
        data=sorted_df_new,
        x='Fold Enrichment', # Flipped axis
        y='plot_index',  # Plot against the unique index
        hue='Analysis', # Use 'Analysis' to differentiate the bars
        palette='viridis',
        dodge=False # Important: ensures each Combined_Label gets one bar, colored by its Analysis
    )

    plt.title('Top 5 GO Biological Process Terms by Fold Enrichment Across New Analyses (Vertical)') # Updated title
    plt.xlabel('Fold Enrichment') # Flipped label
    plt.ylabel('GO Term (Grouped by Analysis)') # Flipped label

    # Set y-axis ticks and labels using the Combined_Label from the sorted DataFrame
    plt.yticks(ticks=sorted_df_new['plot_index'], labels=sorted_df_new['Combined_Label'], rotation=0, ha='right')
    plt.legend(title='Analysis File', bbox_to_anchor=(1.01, 1), loc='upper left') # Place legend outside, adjusted slightly

    # Add horizontal lines to separate analyses
    ax = plt.gca() # Get the current axes
    # Calculate group boundaries dynamically
    group_indices_new = sorted_df_new.groupby('Analysis').size().cumsum().tolist()
    # The lines should be placed before the start of each new group
    line_positions_new = [idx - 0.5 for idx in group_indices_new[:-1]] # Exclude the last cumulative sum as it's the total number of rows

    for pos in line_positions_new:
        ax.axhline(y=pos, color='grey', linestyle='--', linewidth=1.5, alpha=0.7)


    plt.tight_layout() # Adjust layout to prevent overlapping elements

    combined_plot_output_path_new = os.path.join(new_output_plot_dir, 'combined_top5_go_terms_single_plot_new_folder_vertical.png')
    plt.savefig(combined_plot_output_path_new)
    plt.show()
    print(f"Combined plot for new folder saved to: {combined_plot_output_path_new}")
else:
    print("No combined data to plot for the new folder. The 'combined_go_df_new' is either not created or empty.")

"""### Combined Horizontal Plot for New Folder GO Enrichment Results"""

import matplotlib.pyplot as plt
import seaborn as sns
import os

new_output_plot_dir = '/content/drive/MyDrive/final_IDRs_GO/go_enrichment_plots_unknown/'

if 'combined_go_df_new' in locals() and not combined_go_df_new.empty:
    plt.figure(figsize=(25, 12))

    plt.rcParams['axes.titlesize'] = 16
    plt.rcParams['axes.labelsize'] = 14
    plt.rcParams['xtick.labelsize'] = 10
    plt.rcParams['ytick.labelsize'] = 8
    plt.rcParams['legend.fontsize'] = 10

    sorted_df_new = combined_go_df_new.sort_values(by=['Analysis', 'Fold Enrichment'], ascending=[True, False])
    sorted_df_new['Combined_Label'] = sorted_df_new['Term'].apply(lambda x: x.split(' (GO:')[0])

    # Create a unique index for plotting, to ensure each bar has its own position
    sorted_df_new['plot_index'] = range(len(sorted_df_new))

    sns.barplot(
        data=sorted_df_new,
        x='plot_index',
        y='Fold Enrichment',
        hue='Analysis',
        palette='viridis',
        dodge=False
    )

    plt.title('Top 5 GO Biological Process Terms by Fold Enrichment Across New Analyses (Horizontal)')
    plt.xlabel('GO Term (Grouped by Analysis)')
    plt.ylabel('Fold Enrichment')

    # Set x-axis ticks and labels using the Combined_Label from the sorted DataFrame
    plt.xticks(ticks=sorted_df_new['plot_index'], labels=sorted_df_new['Combined_Label'], rotation=90, ha='center')
    plt.legend(title='Analysis File', bbox_to_anchor=(1.01, 1), loc='upper left')

    # Add vertical lines to separate analyses
    ax = plt.gca()
    # Calculate group boundaries dynamically
    group_indices_new = sorted_df_new.groupby('Analysis').size().cumsum().tolist()
    # The lines should be placed before the start of each new group
    line_positions_new = [idx - 0.5 for idx in group_indices_new[:-1]] # Exclude the last cumulative sum as it's the total number of rows

    for pos in line_positions_new:
        ax.axvline(x=pos, color='grey', linestyle='--', linewidth=1.5, alpha=0.7)

    plt.tight_layout()

    combined_plot_output_path_new_horizontal = os.path.join(new_output_plot_dir, 'combined_top5_go_terms_single_plot_new_folder_horizontal.png')
    plt.savefig(combined_plot_output_path_new_horizontal)
    plt.show()
    print(f"Combined horizontal plot for new folder saved to: {combined_plot_output_path_new_horizontal}")
else:
    print("No combined data to plot for the new folder. The 'combined_go_df_new' is either not created or empty.")